services:
  mqtt-api-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mqtt-api-service
    restart: unless-stopped
    env_file:
      - ../config/mqtt-api-service/mqtt-api-service.env
    volumes:
      - ../config/mqtt-api-service/certs:/app/certs:ro
    networks:
      - saas-network

networks:
  saas-network:
    external: true
    name: saas-network
