syntax = "proto3";

package devicecontrol;

option go_package = "mqtt-api-service/internal/adapters/grpc/proto/devicecontrol";

service DeviceControlService {

  rpc SetPower(SetPowerRequest)
      returns (CommandResponse);

  rpc SetTemperature(SetTemperatureRequest)
      returns (CommandResponse);

  rpc SetAirFlow(SetAirFlowRequest)
      returns (CommandResponse);

  rpc SetOperationMode(SetOperationModeRequest)
      returns (CommandResponse);

  rpc SetOscillation(SetOscillationRequest)
      returns (CommandResponse);

  rpc SetPowerSave(SetPowerSaveRequest)
      returns (CommandResponse);
}


message SetPowerRequest {
  string device_id = 1;
  bool power = 2;
}


message SetTemperatureRequest {
  string device_id = 1;
  double temperature = 2;
}


message SetAirFlowRequest {
  string device_id = 1;

  // LOW, MID, HIGH, AUTO
  string strength = 2;
}


message SetOperationModeRequest {
  string device_id = 1;

  // COOL, AUTO, FAN, AIR_DRY
  string mode = 2;
}


message SetOscillationRequest {
  string device_id = 1;
  bool enabled = 2;
}


message SetPowerSaveRequest {
  string device_id = 1;
  bool enabled = 2;
}


message CommandResponse {
  bool success = 1;
  string message = 2;
}