// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.35.1
// source: internal/adapters/grpc/proto/devicecontrol/devicecontrol.proto

package devicecontrol

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	DeviceControlService_SetPower_FullMethodName         = "/devicecontrol.DeviceControlService/SetPower"
	DeviceControlService_SetTemperature_FullMethodName   = "/devicecontrol.DeviceControlService/SetTemperature"
	DeviceControlService_SetAirFlow_FullMethodName       = "/devicecontrol.DeviceControlService/SetAirFlow"
	DeviceControlService_SetOperationMode_FullMethodName = "/devicecontrol.DeviceControlService/SetOperationMode"
	DeviceControlService_SetOscillation_FullMethodName   = "/devicecontrol.DeviceControlService/SetOscillation"
	DeviceControlService_SetPowerSave_FullMethodName     = "/devicecontrol.DeviceControlService/SetPowerSave"
)

// DeviceControlServiceClient is the client API for DeviceControlService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DeviceControlServiceClient interface {
	SetPower(ctx context.Context, in *SetPowerRequest, opts ...grpc.CallOption) (*CommandResponse, error)
	SetTemperature(ctx context.Context, in *SetTemperatureRequest, opts ...grpc.CallOption) (*CommandResponse, error)
	SetAirFlow(ctx context.Context, in *SetAirFlowRequest, opts ...grpc.CallOption) (*CommandResponse, error)
	SetOperationMode(ctx context.Context, in *SetOperationModeRequest, opts ...grpc.CallOption) (*CommandResponse, error)
	SetOscillation(ctx context.Context, in *SetOscillationRequest, opts ...grpc.CallOption) (*CommandResponse, error)
	SetPowerSave(ctx context.Context, in *SetPowerSaveRequest, opts ...grpc.CallOption) (*CommandResponse, error)
}

type deviceControlServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewDeviceControlServiceClient(cc grpc.ClientConnInterface) DeviceControlServiceClient {
	return &deviceControlServiceClient{cc}
}

func (c *deviceControlServiceClient) SetPower(ctx context.Context, in *SetPowerRequest, opts ...grpc.CallOption) (*CommandResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CommandResponse)
	err := c.cc.Invoke(ctx, DeviceControlService_SetPower_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *deviceControlServiceClient) SetTemperature(ctx context.Context, in *SetTemperatureRequest, opts ...grpc.CallOption) (*CommandResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CommandResponse)
	err := c.cc.Invoke(ctx, DeviceControlService_SetTemperature_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *deviceControlServiceClient) SetAirFlow(ctx context.Context, in *SetAirFlowRequest, opts ...grpc.CallOption) (*CommandResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CommandResponse)
	err := c.cc.Invoke(ctx, DeviceControlService_SetAirFlow_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *deviceControlServiceClient) SetOperationMode(ctx context.Context, in *SetOperationModeRequest, opts ...grpc.CallOption) (*CommandResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CommandResponse)
	err := c.cc.Invoke(ctx, DeviceControlService_SetOperationMode_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *deviceControlServiceClient) SetOscillation(ctx context.Context, in *SetOscillationRequest, opts ...grpc.CallOption) (*CommandResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CommandResponse)
	err := c.cc.Invoke(ctx, DeviceControlService_SetOscillation_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *deviceControlServiceClient) SetPowerSave(ctx context.Context, in *SetPowerSaveRequest, opts ...grpc.CallOption) (*CommandResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CommandResponse)
	err := c.cc.Invoke(ctx, DeviceControlService_SetPowerSave_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DeviceControlServiceServer is the server API for DeviceControlService service.
// All implementations must embed UnimplementedDeviceControlServiceServer
// for forward compatibility.
type DeviceControlServiceServer interface {
	SetPower(context.Context, *SetPowerRequest) (*CommandResponse, error)
	SetTemperature(context.Context, *SetTemperatureRequest) (*CommandResponse, error)
	SetAirFlow(context.Context, *SetAirFlowRequest) (*CommandResponse, error)
	SetOperationMode(context.Context, *SetOperationModeRequest) (*CommandResponse, error)
	SetOscillation(context.Context, *SetOscillationRequest) (*CommandResponse, error)
	SetPowerSave(context.Context, *SetPowerSaveRequest) (*CommandResponse, error)
	mustEmbedUnimplementedDeviceControlServiceServer()
}

// UnimplementedDeviceControlServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDeviceControlServiceServer struct{}

func (UnimplementedDeviceControlServiceServer) SetPower(context.Context, *SetPowerRequest) (*CommandResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SetPower not implemented")
}
func (UnimplementedDeviceControlServiceServer) SetTemperature(context.Context, *SetTemperatureRequest) (*CommandResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SetTemperature not implemented")
}
func (UnimplementedDeviceControlServiceServer) SetAirFlow(context.Context, *SetAirFlowRequest) (*CommandResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SetAirFlow not implemented")
}
func (UnimplementedDeviceControlServiceServer) SetOperationMode(context.Context, *SetOperationModeRequest) (*CommandResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SetOperationMode not implemented")
}
func (UnimplementedDeviceControlServiceServer) SetOscillation(context.Context, *SetOscillationRequest) (*CommandResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SetOscillation not implemented")
}
func (UnimplementedDeviceControlServiceServer) SetPowerSave(context.Context, *SetPowerSaveRequest) (*CommandResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SetPowerSave not implemented")
}
func (UnimplementedDeviceControlServiceServer) mustEmbedUnimplementedDeviceControlServiceServer() {}
func (UnimplementedDeviceControlServiceServer) testEmbeddedByValue()                              {}

// UnsafeDeviceControlServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DeviceControlServiceServer will
// result in compilation errors.
type UnsafeDeviceControlServiceServer interface {
	mustEmbedUnimplementedDeviceControlServiceServer()
}

func RegisterDeviceControlServiceServer(s grpc.ServiceRegistrar, srv DeviceControlServiceServer) {
	// If the following call panics, it indicates UnimplementedDeviceControlServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&DeviceControlService_ServiceDesc, srv)
}

func _DeviceControlService_SetPower_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetPowerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeviceControlServiceServer).SetPower(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DeviceControlService_SetPower_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeviceControlServiceServer).SetPower(ctx, req.(*SetPowerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DeviceControlService_SetTemperature_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetTemperatureRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeviceControlServiceServer).SetTemperature(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DeviceControlService_SetTemperature_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeviceControlServiceServer).SetTemperature(ctx, req.(*SetTemperatureRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DeviceControlService_SetAirFlow_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetAirFlowRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeviceControlServiceServer).SetAirFlow(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DeviceControlService_SetAirFlow_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeviceControlServiceServer).SetAirFlow(ctx, req.(*SetAirFlowRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DeviceControlService_SetOperationMode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetOperationModeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeviceControlServiceServer).SetOperationMode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DeviceControlService_SetOperationMode_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeviceControlServiceServer).SetOperationMode(ctx, req.(*SetOperationModeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DeviceControlService_SetOscillation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetOscillationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeviceControlServiceServer).SetOscillation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DeviceControlService_SetOscillation_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeviceControlServiceServer).SetOscillation(ctx, req.(*SetOscillationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DeviceControlService_SetPowerSave_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetPowerSaveRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeviceControlServiceServer).SetPowerSave(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DeviceControlService_SetPowerSave_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeviceControlServiceServer).SetPowerSave(ctx, req.(*SetPowerSaveRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// DeviceControlService_ServiceDesc is the grpc.ServiceDesc for DeviceControlService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DeviceControlService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "devicecontrol.DeviceControlService",
	HandlerType: (*DeviceControlServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SetPower",
			Handler:    _DeviceControlService_SetPower_Handler,
		},
		{
			MethodName: "SetTemperature",
			Handler:    _DeviceControlService_SetTemperature_Handler,
		},
		{
			MethodName: "SetAirFlow",
			Handler:    _DeviceControlService_SetAirFlow_Handler,
		},
		{
			MethodName: "SetOperationMode",
			Handler:    _DeviceControlService_SetOperationMode_Handler,
		},
		{
			MethodName: "SetOscillation",
			Handler:    _DeviceControlService_SetOscillation_Handler,
		},
		{
			MethodName: "SetPowerSave",
			Handler:    _DeviceControlService_SetPowerSave_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "internal/adapters/grpc/proto/devicecontrol/devicecontrol.proto",
}
