// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: internal/adapters/grpc/proto/tracking/tracking.proto

package tracking

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RawMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Topic         string                 `protobuf:"bytes,1,opt,name=topic,proto3" json:"topic,omitempty"`
	Payload       []byte                 `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
	Qos           int32                  `protobuf:"varint,3,opt,name=qos,proto3" json:"qos,omitempty"`
	Retain        bool                   `protobuf:"varint,4,opt,name=retain,proto3" json:"retain,omitempty"`
	ReceivedAt    string                 `protobuf:"bytes,5,opt,name=received_at,json=receivedAt,proto3" json:"received_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RawMessage) Reset() {
	*x = RawMessage{}
	mi := &file_internal_adapters_grpc_proto_tracking_tracking_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RawMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RawMessage) ProtoMessage() {}

func (x *RawMessage) ProtoReflect() protoreflect.Message {
	mi := &file_internal_adapters_grpc_proto_tracking_tracking_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RawMessage.ProtoReflect.Descriptor instead.
func (*RawMessage) Descriptor() ([]byte, []int) {
	return file_internal_adapters_grpc_proto_tracking_tracking_proto_rawDescGZIP(), []int{0}
}

func (x *RawMessage) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

func (x *RawMessage) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *RawMessage) GetQos() int32 {
	if x != nil {
		return x.Qos
	}
	return 0
}

func (x *RawMessage) GetRetain() bool {
	if x != nil {
		return x.Retain
	}
	return false
}

func (x *RawMessage) GetReceivedAt() string {
	if x != nil {
		return x.ReceivedAt
	}
	return ""
}

type Ack struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Ack) Reset() {
	*x = Ack{}
	mi := &file_internal_adapters_grpc_proto_tracking_tracking_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ack) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ack) ProtoMessage() {}

func (x *Ack) ProtoReflect() protoreflect.Message {
	mi := &file_internal_adapters_grpc_proto_tracking_tracking_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ack.ProtoReflect.Descriptor instead.
func (*Ack) Descriptor() ([]byte, []int) {
	return file_internal_adapters_grpc_proto_tracking_tracking_proto_rawDescGZIP(), []int{1}
}

func (x *Ack) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

var File_internal_adapters_grpc_proto_tracking_tracking_proto protoreflect.FileDescriptor

const file_internal_adapters_grpc_proto_tracking_tracking_proto_rawDesc = "" +
	"\n" +
	"4internal/adapters/grpc/proto/tracking/tracking.proto\x12\btracking\"\x87\x01\n" +
	"\n" +
	"RawMessage\x12\x14\n" +
	"\x05topic\x18\x01 \x01(\tR\x05topic\x12\x18\n" +
	"\apayload\x18\x02 \x01(\fR\apayload\x12\x10\n" +
	"\x03qos\x18\x03 \x01(\x05R\x03qos\x12\x16\n" +
	"\x06retain\x18\x04 \x01(\bR\x06retain\x12\x1f\n" +
	"\vreceived_at\x18\x05 \x01(\tR\n" +
	"receivedAt\"\x15\n" +
	"\x03Ack\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok2C\n" +
	"\x0fTrackingService\x120\n" +
	"\tIngestRaw\x12\x14.tracking.RawMessage\x1a\r.tracking.AckB?Z=github.com/aaron/mqtt-adapter-service/proto/tracking;trackingb\x06proto3"

var (
	file_internal_adapters_grpc_proto_tracking_tracking_proto_rawDescOnce sync.Once
	file_internal_adapters_grpc_proto_tracking_tracking_proto_rawDescData []byte
)

func file_internal_adapters_grpc_proto_tracking_tracking_proto_rawDescGZIP() []byte {
	file_internal_adapters_grpc_proto_tracking_tracking_proto_rawDescOnce.Do(func() {
		file_internal_adapters_grpc_proto_tracking_tracking_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_adapters_grpc_proto_tracking_tracking_proto_rawDesc), len(file_internal_adapters_grpc_proto_tracking_tracking_proto_rawDesc)))
	})
	return file_internal_adapters_grpc_proto_tracking_tracking_proto_rawDescData
}

var file_internal_adapters_grpc_proto_tracking_tracking_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_internal_adapters_grpc_proto_tracking_tracking_proto_goTypes = []any{
	(*RawMessage)(nil), // 0: tracking.RawMessage
	(*Ack)(nil),        // 1: tracking.Ack
}
var file_internal_adapters_grpc_proto_tracking_tracking_proto_depIdxs = []int32{
	0, // 0: tracking.TrackingService.IngestRaw:input_type -> tracking.RawMessage
	1, // 1: tracking.TrackingService.IngestRaw:output_type -> tracking.Ack
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_internal_adapters_grpc_proto_tracking_tracking_proto_init() }
func file_internal_adapters_grpc_proto_tracking_tracking_proto_init() {
	if File_internal_adapters_grpc_proto_tracking_tracking_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_adapters_grpc_proto_tracking_tracking_proto_rawDesc), len(file_internal_adapters_grpc_proto_tracking_tracking_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_adapters_grpc_proto_tracking_tracking_proto_goTypes,
		DependencyIndexes: file_internal_adapters_grpc_proto_tracking_tracking_proto_depIdxs,
		MessageInfos:      file_internal_adapters_grpc_proto_tracking_tracking_proto_msgTypes,
	}.Build()
	File_internal_adapters_grpc_proto_tracking_tracking_proto = out.File
	file_internal_adapters_grpc_proto_tracking_tracking_proto_goTypes = nil
	file_internal_adapters_grpc_proto_tracking_tracking_proto_depIdxs = nil
}
