// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: internal/adapters/grpc/proto/tracking.proto

package tracking

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EventCode int32

const (
	EventCode_EVENT_CODE_TRACKING            EventCode = 0
	EventCode_EVENT_CODE_DEVICE_STATE_CHANGE EventCode = 1
	EventCode_EVENT_CODE_POWER_ON            EventCode = 2
	EventCode_EVENT_CODE_POWER_OFF           EventCode = 3
	EventCode_EVENT_CODE_TEMPERATURE_CHANGE  EventCode = 4
)

// Enum value maps for EventCode.
var (
	EventCode_name = map[int32]string{
		0: "EVENT_CODE_TRACKING",
		1: "EVENT_CODE_DEVICE_STATE_CHANGE",
		2: "EVENT_CODE_POWER_ON",
		3: "EVENT_CODE_POWER_OFF",
		4: "EVENT_CODE_TEMPERATURE_CHANGE",
	}
	EventCode_value = map[string]int32{
		"EVENT_CODE_TRACKING":            0,
		"EVENT_CODE_DEVICE_STATE_CHANGE": 1,
		"EVENT_CODE_POWER_ON":            2,
		"EVENT_CODE_POWER_OFF":           3,
		"EVENT_CODE_TEMPERATURE_CHANGE":  4,
	}
)

func (x EventCode) Enum() *EventCode {
	p := new(EventCode)
	*p = x
	return p
}

func (x EventCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EventCode) Descriptor() protoreflect.EnumDescriptor {
	return file_internal_adapters_grpc_proto_tracking_proto_enumTypes[0].Descriptor()
}

func (EventCode) Type() protoreflect.EnumType {
	return &file_internal_adapters_grpc_proto_tracking_proto_enumTypes[0]
}

func (x EventCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EventCode.Descriptor instead.
func (EventCode) EnumDescriptor() ([]byte, []int) {
	return file_internal_adapters_grpc_proto_tracking_proto_rawDescGZIP(), []int{0}
}

type TemperaturePayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Current       float64                `protobuf:"fixed64,1,opt,name=current,proto3" json:"current,omitempty"`
	Target        float64                `protobuf:"fixed64,2,opt,name=target,proto3" json:"target,omitempty"`
	Unit          string                 `protobuf:"bytes,3,opt,name=unit,proto3" json:"unit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TemperaturePayload) Reset() {
	*x = TemperaturePayload{}
	mi := &file_internal_adapters_grpc_proto_tracking_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TemperaturePayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TemperaturePayload) ProtoMessage() {}

func (x *TemperaturePayload) ProtoReflect() protoreflect.Message {
	mi := &file_internal_adapters_grpc_proto_tracking_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TemperaturePayload.ProtoReflect.Descriptor instead.
func (*TemperaturePayload) Descriptor() ([]byte, []int) {
	return file_internal_adapters_grpc_proto_tracking_proto_rawDescGZIP(), []int{0}
}

func (x *TemperaturePayload) GetCurrent() float64 {
	if x != nil {
		return x.Current
	}
	return 0
}

func (x *TemperaturePayload) GetTarget() float64 {
	if x != nil {
		return x.Target
	}
	return 0
}

func (x *TemperaturePayload) GetUnit() string {
	if x != nil {
		return x.Unit
	}
	return ""
}

type LGTelemetryPayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventCode     EventCode              `protobuf:"varint,1,opt,name=event_code,json=eventCode,proto3,enum=tracking.v1.EventCode" json:"event_code,omitempty"`
	DeviceType    string                 `protobuf:"bytes,2,opt,name=device_type,json=deviceType,proto3" json:"device_type,omitempty"`
	Power         bool                   `protobuf:"varint,3,opt,name=power,proto3" json:"power,omitempty"`
	Temperature   *TemperaturePayload    `protobuf:"bytes,4,opt,name=temperature,proto3" json:"temperature,omitempty"`
	Humidity      *float64               `protobuf:"fixed64,5,opt,name=humidity,proto3,oneof" json:"humidity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LGTelemetryPayload) Reset() {
	*x = LGTelemetryPayload{}
	mi := &file_internal_adapters_grpc_proto_tracking_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LGTelemetryPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LGTelemetryPayload) ProtoMessage() {}

func (x *LGTelemetryPayload) ProtoReflect() protoreflect.Message {
	mi := &file_internal_adapters_grpc_proto_tracking_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LGTelemetryPayload.ProtoReflect.Descriptor instead.
func (*LGTelemetryPayload) Descriptor() ([]byte, []int) {
	return file_internal_adapters_grpc_proto_tracking_proto_rawDescGZIP(), []int{1}
}

func (x *LGTelemetryPayload) GetEventCode() EventCode {
	if x != nil {
		return x.EventCode
	}
	return EventCode_EVENT_CODE_TRACKING
}

func (x *LGTelemetryPayload) GetDeviceType() string {
	if x != nil {
		return x.DeviceType
	}
	return ""
}

func (x *LGTelemetryPayload) GetPower() bool {
	if x != nil {
		return x.Power
	}
	return false
}

func (x *LGTelemetryPayload) GetTemperature() *TemperaturePayload {
	if x != nil {
		return x.Temperature
	}
	return nil
}

func (x *LGTelemetryPayload) GetHumidity() float64 {
	if x != nil && x.Humidity != nil {
		return *x.Humidity
	}
	return 0
}

type NormalizedMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Imei          string                 `protobuf:"bytes,1,opt,name=imei,proto3" json:"imei,omitempty"`
	ReceivedAt    string                 `protobuf:"bytes,2,opt,name=received_at,json=receivedAt,proto3" json:"received_at,omitempty"`
	Topic         string                 `protobuf:"bytes,3,opt,name=topic,proto3" json:"topic,omitempty"`
	Payload       *LGTelemetryPayload    `protobuf:"bytes,4,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NormalizedMessage) Reset() {
	*x = NormalizedMessage{}
	mi := &file_internal_adapters_grpc_proto_tracking_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NormalizedMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NormalizedMessage) ProtoMessage() {}

func (x *NormalizedMessage) ProtoReflect() protoreflect.Message {
	mi := &file_internal_adapters_grpc_proto_tracking_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NormalizedMessage.ProtoReflect.Descriptor instead.
func (*NormalizedMessage) Descriptor() ([]byte, []int) {
	return file_internal_adapters_grpc_proto_tracking_proto_rawDescGZIP(), []int{2}
}

func (x *NormalizedMessage) GetImei() string {
	if x != nil {
		return x.Imei
	}
	return ""
}

func (x *NormalizedMessage) GetReceivedAt() string {
	if x != nil {
		return x.ReceivedAt
	}
	return ""
}

func (x *NormalizedMessage) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

func (x *NormalizedMessage) GetPayload() *LGTelemetryPayload {
	if x != nil {
		return x.Payload
	}
	return nil
}

type Ack struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Ack) Reset() {
	*x = Ack{}
	mi := &file_internal_adapters_grpc_proto_tracking_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ack) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ack) ProtoMessage() {}

func (x *Ack) ProtoReflect() protoreflect.Message {
	mi := &file_internal_adapters_grpc_proto_tracking_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ack.ProtoReflect.Descriptor instead.
func (*Ack) Descriptor() ([]byte, []int) {
	return file_internal_adapters_grpc_proto_tracking_proto_rawDescGZIP(), []int{3}
}

func (x *Ack) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *Ack) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_internal_adapters_grpc_proto_tracking_proto protoreflect.FileDescriptor

const file_internal_adapters_grpc_proto_tracking_proto_rawDesc = "" +
	"\n" +
	"+internal/adapters/grpc/proto/tracking.proto\x12\vtracking.v1\"Z\n" +
	"\x12TemperaturePayload\x12\x18\n" +
	"\acurrent\x18\x01 \x01(\x01R\acurrent\x12\x16\n" +
	"\x06target\x18\x02 \x01(\x01R\x06target\x12\x12\n" +
	"\x04unit\x18\x03 \x01(\tR\x04unit\"\xf3\x01\n" +
	"\x12LGTelemetryPayload\x125\n" +
	"\n" +
	"event_code\x18\x01 \x01(\x0e2\x16.tracking.v1.EventCodeR\teventCode\x12\x1f\n" +
	"\vdevice_type\x18\x02 \x01(\tR\n" +
	"deviceType\x12\x14\n" +
	"\x05power\x18\x03 \x01(\bR\x05power\x12A\n" +
	"\vtemperature\x18\x04 \x01(\v2\x1f.tracking.v1.TemperaturePayloadR\vtemperature\x12\x1f\n" +
	"\bhumidity\x18\x05 \x01(\x01H\x00R\bhumidity\x88\x01\x01B\v\n" +
	"\t_humidity\"\x99\x01\n" +
	"\x11NormalizedMessage\x12\x12\n" +
	"\x04imei\x18\x01 \x01(\tR\x04imei\x12\x1f\n" +
	"\vreceived_at\x18\x02 \x01(\tR\n" +
	"receivedAt\x12\x14\n" +
	"\x05topic\x18\x03 \x01(\tR\x05topic\x129\n" +
	"\apayload\x18\x04 \x01(\v2\x1f.tracking.v1.LGTelemetryPayloadR\apayload\"9\n" +
	"\x03Ack\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage*\x9e\x01\n" +
	"\tEventCode\x12\x17\n" +
	"\x13EVENT_CODE_TRACKING\x10\x00\x12\"\n" +
	"\x1eEVENT_CODE_DEVICE_STATE_CHANGE\x10\x01\x12\x17\n" +
	"\x13EVENT_CODE_POWER_ON\x10\x02\x12\x18\n" +
	"\x14EVENT_CODE_POWER_OFF\x10\x03\x12!\n" +
	"\x1dEVENT_CODE_TEMPERATURE_CHANGE\x10\x042S\n" +
	"\x0fTrackingService\x12@\n" +
	"\fPublishEvent\x12\x1e.tracking.v1.NormalizedMessage\x1a\x10.tracking.v1.AckBAZ?mqtt-api-service/internal/adapters/grpc/proto/tracking;trackingb\x06proto3"

var (
	file_internal_adapters_grpc_proto_tracking_proto_rawDescOnce sync.Once
	file_internal_adapters_grpc_proto_tracking_proto_rawDescData []byte
)

func file_internal_adapters_grpc_proto_tracking_proto_rawDescGZIP() []byte {
	file_internal_adapters_grpc_proto_tracking_proto_rawDescOnce.Do(func() {
		file_internal_adapters_grpc_proto_tracking_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_adapters_grpc_proto_tracking_proto_rawDesc), len(file_internal_adapters_grpc_proto_tracking_proto_rawDesc)))
	})
	return file_internal_adapters_grpc_proto_tracking_proto_rawDescData
}

var file_internal_adapters_grpc_proto_tracking_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_internal_adapters_grpc_proto_tracking_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_internal_adapters_grpc_proto_tracking_proto_goTypes = []any{
	(EventCode)(0),             // 0: tracking.v1.EventCode
	(*TemperaturePayload)(nil), // 1: tracking.v1.TemperaturePayload
	(*LGTelemetryPayload)(nil), // 2: tracking.v1.LGTelemetryPayload
	(*NormalizedMessage)(nil),  // 3: tracking.v1.NormalizedMessage
	(*Ack)(nil),                // 4: tracking.v1.Ack
}
var file_internal_adapters_grpc_proto_tracking_proto_depIdxs = []int32{
	0, // 0: tracking.v1.LGTelemetryPayload.event_code:type_name -> tracking.v1.EventCode
	1, // 1: tracking.v1.LGTelemetryPayload.temperature:type_name -> tracking.v1.TemperaturePayload
	2, // 2: tracking.v1.NormalizedMessage.payload:type_name -> tracking.v1.LGTelemetryPayload
	3, // 3: tracking.v1.TrackingService.PublishEvent:input_type -> tracking.v1.NormalizedMessage
	4, // 4: tracking.v1.TrackingService.PublishEvent:output_type -> tracking.v1.Ack
	4, // [4:5] is the sub-list for method output_type
	3, // [3:4] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_internal_adapters_grpc_proto_tracking_proto_init() }
func file_internal_adapters_grpc_proto_tracking_proto_init() {
	if File_internal_adapters_grpc_proto_tracking_proto != nil {
		return
	}
	file_internal_adapters_grpc_proto_tracking_proto_msgTypes[1].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_adapters_grpc_proto_tracking_proto_rawDesc), len(file_internal_adapters_grpc_proto_tracking_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_adapters_grpc_proto_tracking_proto_goTypes,
		DependencyIndexes: file_internal_adapters_grpc_proto_tracking_proto_depIdxs,
		EnumInfos:         file_internal_adapters_grpc_proto_tracking_proto_enumTypes,
		MessageInfos:      file_internal_adapters_grpc_proto_tracking_proto_msgTypes,
	}.Build()
	File_internal_adapters_grpc_proto_tracking_proto = out.File
	file_internal_adapters_grpc_proto_tracking_proto_goTypes = nil
	file_internal_adapters_grpc_proto_tracking_proto_depIdxs = nil
}
